name: Release
on:
  push:
    branches:
      - master

# Environment variables available to all jobs and steps in this workflow
env:
  NODE_VERSION: 14
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Code Quality and Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Restore Cached Packages
        uses: actions/cache@master
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{env.NODE_VERSION}}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Install
        run: npm ci

      - name: Code Quality and Style
        run: |
          npm run lint
          npm run prettier:check:all
          npm run test
          npm run build

  semantic-release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    needs: test
    name: Semantic Release
    env:
      GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    steps:
      - uses: actions/checkout@v2
      - name: Semantic Release
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm ci
          npm run build
          npm run semantic-release

  merge-release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    needs: semantic-release
    runs-on: ubuntu-latest
    name: Merge release to develop
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
          token: ${{ secrets.ACTIONS_TOKEN }}
          fetch-depth: 0
      - run: |
          git fetch
          git config --global user.email "actions@github.com"
          git config --global user.name "Github"
          git merge origin/master
          git push --force
